### ISSUE TITLE
TEMAS COMUNES - COMENTARIOS

### ISSUE THREAD

**Issue by EML2008** [joniborda/LYC06#6]
Deberán estar delimitados por “***/” y “/***” y podrán estar anidados en un solo nivel.
Ejemplo1:
***/ Realizo una selección /***
IF (a <= 30)
b = ”correcto” ***/ asignación string /*** ENDIF
Ejemplo2:
***/ Así son los comentarios en el 1°Cuat de LyC /*** Comentario ***/ /***

**Comment by serMR** [comment]
SUBCOMENTARIO   "/***"({CARACTER}|" "|\")+"***/"
COMENTARIO  "***/"({CARACTER}|" "|\"|{SUBCOMENTARIO})+"/***"

%%

al final del todo..
{COMENTARIO}
