### ISSUE TITLE
TEMAS COMUNES - DECLARACIONES

### ISSUE THREAD

**Issue by EML2008** [joniborda/LYC06#9]
Todas las variables deberán ser declaradas de la siguiente manera:
DEFVAR
Tipo de Variable : Lista de Variables (1)
ENDDEF
El bloque delimitado con DEFVAR – VAR puede contener varias líneas de declaración de la forma (1)
El bloque delimitado con DEFVAR – VAR no puede estar vacío
El Tipo de Variable debe ser único para cada línea de la forma (1)
Un tipo de variable podría estar en más de una línea de la forma (1)
La Lista de variables debe separarse por punto y coma y no puede estar vacía
Ejemplos de formato:
DEFVAR
FLOAT : a1; b1
STRING: variable1
FLOAT : p1; p2; p3
INT : a;b
ENDDEF

**Comment by ilandaburu** [comment]
Done
